### ISSUE TITLE
bunsen-configs-base 13.0.2-0.3  source code is not in github repository

### ISSUE THREAD

**Issue by johnraff** [01micko/01micko.github.io#6]
While the source code of bunsen-configs-base 13.0.2-0.3 is available in the tarballs here: https://github.com/01micko/01micko.github.io/tree/main/debian/pool/main/b/bunsen-configs-base
it is not viewable in any of the branches of bunsen-configs.

The latest version there is 13.0-1, the same as in the BunsenLabs repository.
There is a jump from 13.0 to 13.0.2 with no information about the changes from 13.0 to 13.0.1 and 13.0.1 to 13.0.2

While strictly speaking the tarballs alone are enough, it would help developers if you built the tarballs of packages hosted here from publicly viewable git repositories. In this case, a branch of the bunsen-configs repo: https://github.com/01micko/bunsen-configs/

**Comment by 01micko** [comment]
I'm still very much chicken and egg with netinstall and configs!

What I might do is create a new repo named bunsen-wayland-configs or something such that I don't have to keep bumping "official" versions every time I find a bug in netinstall! I do need to upload to the repo for proper testing.

It of course could be cherry picked later.

I haven't pushed the configs > staging barnch yet and the debian/ stuff is still very WIP.

I'll tidy everything up soon as it is a bit of a mess, not too bad but still. By the weekend close it should start to make some sense.

I won't have any time next week so I'll try and get things right tomorrow.

**Comment by 01micko** [comment]
I just pushed 'staging' @johnraff 

This is the one you want to look at because it has my mods to `bunsenlabs-session` and user `autostart`

**Comment by johnraff** [comment]
Just noticed the latest commit to 'staging'. Looks good!

**Comment by johnraff** [comment]
> What I might do is create a new repo named bunsen-wayland-configs

In fact I would rather suggest building a new package - with that name, sure - based on your staging branch of bunsen-configs, by adding the entry to debian/control and adding the other files under debian/. That would save you from having to copy over all the content, with the possibility of missing something. Since it's a fresh branch you can still clear out all the unnecessary content with no danger - it'll be available in the other branches if needed.

**Comment by johnraff** [comment]
bunsen-configs-base was removed from this repo. https://github.com/01micko/01micko.github.io/issues/7#issuecomment-2227109302
