### ISSUE TITLE
bunsen-configs-base: some minor issues in the control and changelog files

### ISSUE THREAD

**Issue by johnraff** [01micko/01micko.github.io#8]
The package built successfully for me, with the expected Lintian warnings, but I found some small issues in the debian/control file:

`Source: bunsen-configs-base`
This should refer to the source package `bunsen-configs`

`Build-Depends: debhelper-compat (= 13)`
Should be:
`Build-Depends: debhelper-compat (= 13), help2man, python3, python3-xdg`
`help2man' is needed by the built-in script genman.sh to generate man pages.
The python build-depends are needed to build bl-xdg-autostart.
In fact, the bunsen-configs-base binary package itself might also need a dependency on python3 adding. I think this might be a recent change in Debian - or Lintian - policy.

`Homepage: https://github.com/BunsenLabs/bunsen-configs`
I think this should point to where the code this package was built from is hosted, which is not currently BunsenLabs.
In fact the source code of this repository is not hosted on any git server, so the missing lines:
```
Vcs-Git: 
Vcs-Browser:
```
cannot be provided anyway. These are not mandatory so it's not so important.

As an experimental Wayland package, the `Recommends:` field could use some drastic weeding out, and possible new packages added. 

I don't think that's a high priority though.

---
And in debian/changelog, the first line of the new entry should be:
`  * Non-maintainer upload.`

---
There are a number of other long-standing Lintian Warnings (also in the BL package) which I have decided can be ignored for now.

**Comment by johnraff** [comment]
bunsen-configs-base has been removed from this repo. https://github.com/01micko/01micko.github.io/issues/7#issuecomment-2227109302

**Comment by 01micko** [comment]
> bunsen-configs-base has been removed from this repo. [#7 (comment)](https://github.com/01micko/01micko.github.io/issues/7#issuecomment-2227109302)

It was never there per my comment down the bottom of that post.

> I will rebuild with just wbase in the control file so I can upload

**Comment by johnraff** [comment]
I might have been misled by this statement in the same comment:
> Also, for now I've purged 'bunsen-configs-base' from the repo. 

Anyway, I guess closing this issue was the right thing to do?
