### ISSUE TITLE
hyprlang clashes with libhyprlang2

### ISSUE THREAD

**Issue by 01micko** [01micko/01micko.github.io#9]
[trixie/libhyprlang2](https://packages.debian.org/trixie/libhyprlang2)

Presents a problem for `hyprpicker` and `hyprlock` in the repo @hhhorb 

They both need to rebuilt against `libhyprlang2` and I need to purge `hyprlang` from the repo.

No big deal, I can do it, but if you want you can. Let me know.

**Comment by hhhorb** [comment]
Replied here...

https://forums.bunsenlabs.org/viewtopic.php?pid=137979#p137979

Thanks for the heads up!
